### ISSUE TITLE
Find new brand name, logo, images for home page

### ISSUE THREAD

**Issue by irufaan** [irufaan/team-kernel-competition#11]
We need to make new logo , new brand name.

Also need proper images for home page slide then only we can start making presentation video

**Comment by irufaan** [comment]
I recommend ..

1. JIM. Solution
J= Java
I= Irufaan
M= Mehedy

2. China Trade Solution

**Comment by irufaan** [comment]
@BlackPearlCorp , [Use This Folder to Submit Your Works ](https://github.com/irufaan/team-kernel-competition/tree/Provincial-Competition-patch/Team%20Members/Hamunyela%20Chequevara%20Weyulu-%20Developer)

**Comment by BlackPearlCorp** [comment]
I feel it should be a simple and catchy word.

**Comment by irufaan** [comment]
@BlackPearlCorp ,, tell us what you recommend,, then we will decide what is best

**Comment by irufaan** [comment]
@BlackPearlCorp @Hasanzjnu ,,, guys to day we need to decide a brand name, so that we can finish logo and images,,

**Comment by BlackPearlCorp** [comment]
ChinaDealsBest.com
