### ISSUE TITLE
Need to choose the tools for the project

### ISSUE THREAD

**Issue by irufaan** [irufaan/team-kernel-competition#2]
Since we decided to make website so first i want you guys to tell me what are the tools that we need to have to make this website, then we will decide the tools that we will use for this project. for eg, Which server, hosting, plugins, frameworks so on..

**Comment by KingKlaus** [comment]
The hostgator domain name and web hosting is just okay and sufficient if we are to keep it professional and we can use shopify in a more business and commercial scene.....the apache framework will be okay or struts guessing the leader is familiar with struts and can pitch this knowledge (about struts)to the other group members incase they dont fully understand it....and for the kind of website...im okay with anything it should just be challenging to prepare us for the real world programming issues

Thanks.

**Comment by KingKlaus** [comment]
But the hostgator is not free...so maybe as team members we can contribute to make our work look neat and perfectly unique....it only costs about 23dollars...so thats roughly about 5 dollars per person

**Comment by Hasanzjnu** [comment]
Framework:
My opinion is here to use Laravel framework.
Here are the top  benefits of using Laravel framework.

Clean Documentation and MVC Support

The documentation of Laravel is clean, organised and easily understandable. The Model View Controller architecture is supported in Laravel and it helps in bringing a variety of built-in function to select from a better development architecture.

Composer Feature

Laravel uses composer dependency manager for the installation and upgradations of different third-party packages. This feature allows developers to easily manage all the required dependencies instantly. This is very useful for any developers to create applications of any sizes.

Quick Pointer: What we should know about the Composer Tool

The composer does not manage packages, but only handles it. In fact, it allows a developer to manage the packages. The purpose of this tool is not to act as a package manager, but as a dependency manager that helps to declare, install, uninstall, or update the library dependencies. These are the small things that make Laravel the best PHP framework.

Internal Templates

Laravel uses Blade, a lightweight yet powerful templating engine which is pre-installed in it. The blade templates are compiled into plain PHP and cached for optimal performance.

Object Oriented Libraries

Laravel is the only framework that includes a variety of pre-installed libraries. The most popular and useful library of Laravel is the Authentication library. This library has very advanced features for login and database securities.

What are the best authentication features in Laravel’s Authentication Library?

Some of the main features include routing, HTTP authentication, user authentication, and login throttling.

How many Libraries does Laravel Include?

Laravel has over 20 high-level libraries pre-installed.

Artisan Included

It’s a CLI included with Laravel that helps us with a wide set of commands. These commands help us to either make a controller, model, service providers etc. or migrate the database, produce test data using tinker etc. We can view the entire list by typing “php artisan list”. Also, we can create our own command using “php artisan make:command MyCommandExample”.

Database Migrations.

While using Laravel there is no need of database replication for every changes that is being made. Therefore, with no replication needed, a developer cannot logically lose any data. This is how Laravel has made the database migration step just a bit faster and secure. Laravel uses a smart Bcrypt algorithm for encrypting database passwords which eventually makes it the best php framework.

Faster Caching.

With a variety of tools supported, Laravel provides a faster solution to web caching. By using certain pre-built support already available in Laravel for applications like Memcached and Redis, memory caching speed up immensely.

Direct Testing.

Making life just a bit easier for programmers, Laravel has considered the usual mistakes that can happen while programming. The unit testing tool ensures that any new updates made on the application, won’t break it. This saves development time, project money, and personal stress. Direct database testing is one of the best time-saving tools included in Laravel.

Laravel Scout.

This is a unique tool of Laravel that allows a full-text search on all Eloquent ORM modules.

Dynamic Use.

Laravel allows the developers to create small as well as huge applications. This makes Laravel a great and stable framework for any developer working on any size of project. Laravel offers a secure API building structure that can promote building the Hybrid Applications. That is to say you can easily create web and hybrid applications using Laravel’s API feature.

There are several Laravel framework benefits that makes it one of the most affable PHP frameworks. It has done an amazing job by providing all the essential features that developer require for creating web applications, backend database work, and authentication issues. As analyzed above, PHP is known for its ability to integrate with many databases and is a very dynamic language. It has increased the security and productivity at the same time, making Laravel the best PHP framework.

**Comment by Hasanzjnu** [comment]
Plugins:
My opinion is here to use Emmet plugin.
 Advantages of using Emmet:
1.Highly portable
2.Dynamic snippets
3.Ultra-fast coding
4.Customizable
5.Platform for new tools

**Comment by Nicole-Rutagengwa** [comment]
hey guys...hope y'all enjoying your winter break!
so as we learned in the past years we all know the basic tools to make a website as i am reminding you these are the basic tools we need to have beside the tools we need to make this website our leader decided to make..
-The basic tools needed for web design are amazingly simple. Aside from a computer and an internet connection, most of the tools we need to build a website are software programs, some of which may already be on our computer, we need a text or HTML editor, a graphics editor, web browsers, and an FTP client to upload files to our web server.
as kay said before in his comments if we need to use struts we better go through it again as i personally didn't understand the use of struts from the teachers explanation so my suggestion is  if our leader knows more about this it will be much better if he explains this to whoever that doesn't know... thanks!

**Comment by Nicole-Rutagengwa** [comment]
Also from the research i made i guess the **dedicated web server**  is the best here are the reasons why:

The dedicated server is also called as managed servers which are used for hosting your website. In Dedicated servers, the client can lease the entire server. It is very popular compared to shared hosting. In Dedicated servers, the company will have the entire control on servers.

Dedicated servers are mostly housed in data centers. The server hardware will be owned by the provider and support for operating systems of application is also provided. When you are using the dedicated servers, you can enjoy the benefits of high performance, email stability, security, and control. Dedicated servers always cost high, it will be used only by the website that has huge traffic.

**Comment by irufaan** [comment]
@lanicky ⛄ Winter break ❄️ .. ahh its boring for me. 💤  
👍 Nice explanation for basic tools need for web design, 💯 I like That.👌 
From my point of View, 🤔 I dont think we need to use Struct framework. 

🤨For the dedicated web server, its more complicated and costly,, 💳 this server is mainly for serious companies like Banks 💲, So, they need to have all the hardwares , Have you seen 👀 google server room,, its huge 🤖, So, we dont need to buy any servers and hardwares,, just ask someone who already have and invested for server and ask them to share that server to us,, thats is known as shared hosting. Therefore, shared hosting is better for small business and newly started business. Once we get rich 💰 then have own server and move everything to that server. very simple and cheap. 😎 Plus. come on, its just a competition. 😜

**Comment by irufaan** [comment]
Now only @Ricil work is missing,, Once I get everyone works I will close this task

**Comment by irufaan** [comment]
@KingKlaus I dont want spend any money for this project , even for domain and servers.. I know hostgator have really nice tools and cheap domain.. but , why we need to buy? 😎 I just want everyone to spend time and energy to learn something new and invest time for this project,, No cash or Money. Ok lets say time is also money.. 😜

**Comment by irufaan** [comment]
@Hasanzjnu .. we are not familiar with  Laravel framework. 🤔 I dont think you also even know this framework.. We never studied it. anyway. Good work! 👌 But of course we will use MVC structure but in much easier way,

**Comment by irufaan** [comment]
This website that we are going to build will collect customer emails and details. then later we contact them through email or mobile phone. Mainly this website will act like advertisement platform to show what we can do for customers. Like we will say, we sell most cheapest cars with best quality, if anyone interest in buying from us just email us. because car is expensive .. in the backend we have deals with car companies in china, but customers dont know about that.

**Comment by irufaan** [comment]
@Hasanzjnu  for the Emmet plugin. We need to know what is this plugin, like we need to know what this plugin will do for this website. basically, description. Ok, then we need to know why we need it.

**Comment by Ricil** [comment]
Sorry guys I was lil busy on something. But for me the best framework we need to use is Django
Django is a full-stack open-source framework powered by Python and supports Python version up to 3.4. Full-stack means it provides all stuff needed “out of the box”. Templates, server side, it even generates an admin panel to configure your website without editing the code - kind of CMS but not CMS. So you likely won’t need any other third-party framework to build a powerful website (CSS frameworks don’t count).

These are some of the advantages and features .

All key features are included initially with the framework. Django follows a Model-Template-View (very similar to MVC) architecture to divide logic and views. One of its advantages is using Object Relational Mapper (ORM) to map project’s objects with database tables. As Django natively supports common database engines (MySQL, PostgreSQL, SQLite, Oracle, SQL Server, DB2 and others with additional drivers), it makes migration between them very simple, you won’t need to rewrite or adapt the code – the framework will map everything itself. Cool, isn’t it?

For newbies, if you want to experiment with Django – you don’t need to have a separate web server installed, Django comes with its own lightweight development server.

**Comment by Ricil** [comment]
Irufaan let’s buy

**Comment by Ricil** [comment]
Lol

**Comment by irufaan** [comment]
@Ricil ,, someone is doing some research.. 💯 its very good framework, but it comes with Python. its too soon to use this. maybe after next semester once we learn Python.

**Comment by irufaan** [comment]
@Ricil you give us money then we buy, boss.  😜

**Comment by irufaan** [comment]
@KingKlaus @Hasanzjnu @lanicky @Ricil ,,, Anything else anyone want say or add before I close this task?
