### ISSUE TITLE
Phase #1 to build the Website

### ISSUE THREAD

**Issue by irufaan** [irufaan/team-kernel-competition#3]
![image](https://user-images.githubusercontent.com/18720307/36382127-d5ed584a-15c2-11e8-9963-e4b45f81330b.png)

Build the business brand,
 Logo,
 email,
 Story (About Us), 
FAQ,
 Privacy Policy, 
Terms Of Service, 
 Refund Policy, 
images.

![image](https://user-images.githubusercontent.com/18720307/36382195-18b3a544-15c3-11e8-9e2e-1da361cdaa85.png)

**Comment by irufaan** [comment]
@KingKlaus @Ricil @Hasanzjnu @lanicky I need everyone to recommend me brand name for this website. 
I will make logo and all other pages. 
So totally I need two things from u guys.. 
1. Brand Name
2. Images for the website home page

**Comment by Nicole-Rutagengwa** [comment]
I guess the images should be some of the offers and stuff we have in the company’s website we are to make ...eg: like  types of t cars we sell

**Comment by Nicole-Rutagengwa** [comment]
Or maybe some of the services ,also I think members of the company ‘s pics can be in the about us part like u said @irufaan according to everyone’s role in this .

**Comment by irufaan** [comment]
@lanicky whats everyone's role in this project.. thats what im asking. plus for now i want images for home page and about us page.

**Comment by irufaan** [comment]
and images should be something related to out sourcing industry.. like two businessman shaking their hands and making a deal.. and brand name is important too

**Comment by Nicole-Rutagengwa** [comment]
Let’s wait for other’s ideas we can put both our photos and the services we provide that’s why I said we can put it in (the about us part)

**Comment by Ricil** [comment]
I support Nicole, we can use the pictures of the stuffs in the company as images or our own pictures

**Comment by KingKlaus** [comment]
LightningKernel.com is my suggestion for the website name and for the pictures i feel any pictures will of what our site is about and add our own kernel unique pictures iconoclastically

**Comment by irufaan** [comment]
So, now everyone has their own folder in this repository,, just put the images that you think is best for the website, then later we will decide.  Team Folder is [Click Here](https://github.com/irufaan/team-kernel-competition/tree/master/Team%20Members). Reason why I want you guys to use this folder is just because that will increase your contribution results in github,, Right now no one put anything so no data is recorded in github,, only my data is available. 
![image](https://user-images.githubusercontent.com/18720307/36595702-32784110-18de-11e8-93f2-2d3b03752878.png)

**Comment by KingKlaus** [comment]
Bro will do the work.....hows your graph so high??

**Comment by irufaan** [comment]
@KingKlaus because I did the readMe and I manage everything,, like creating tasks, milestones, project timeline, to do list , so on.  Mededy Suggested some brand names [Click here to see his works](https://github.com/irufaan/team-kernel-competition/tree/master/Team%20Members/Hasan%20Md%20Mehedi-%20Developer)
![image](https://user-images.githubusercontent.com/18720307/36641753-2dde3176-1a70-11e8-9b0c-288514edc8a0.png)
