### ISSUE TITLE
Manufacturing & Processing Machinery

### ISSUE THREAD

**Issue by irufaan** [irufaan/team-kernel-competition#4]
We need find few products we can supply to customers about Manufacturing & Processing Machinery. At least We need 5 products in this category,, more is appriciatable, 

1. All details of the product.
- Description of the product
- Few Images of the product
- Allow Customers to Customize the product ( custom needs such as process method, surface treatment, size, color, logo, etc.)
- Minimum orders that customers can order
- Payment method (L/C, T/T, Western Union etc)
- Delivery details
- Location of the factory, like from which City in China.

2. All Details of the Supplier
- Contact information (Phone Number, Email , factory name, Supplier Name , etc)
- For this category you can either have different factory or just from same factory,, its your choice
- Few Images of the factory and Supplier.
- What deal we have with the factory,, like how we are benefiting by selling products? like monthly salary or commission? or profit share. 

I can recommend some products you can look for,
1. Agriculture Machinery : 3 Row Corn Harvester (4YZP-3L)
2. Plastic & Woodworking Machinery : 1300X2500mm Wooden Door Furniture Crafts Wood Working Machine
3. Machine Tools : Hydraulic Surface Grinding Machine My1022 (540*250mm)
4. Construction Machinery : Mobile Hydraulic Trailer Concrete Pump with Drum Mixer (JBT40-P)
5. Other Machinery & Parts : High Speed Printing and Embossing Napkin Paper Machine

Still you can choose whatever you want from this category.
Again if you still dont understand how you need present this details ,, I can show you sample of one product.. 
![image](https://user-images.githubusercontent.com/18720307/37075846-b89c546e-220e-11e8-9673-6025e0835875.png)
![image](https://user-images.githubusercontent.com/18720307/37076092-e044a222-220f-11e8-86d5-bac09a0c8cc5.png)
![image](https://user-images.githubusercontent.com/18720307/37075875-e08f89b4-220e-11e8-8be5-b3bc79c668ac.png)
![image](https://user-images.githubusercontent.com/18720307/37075889-f65a1fa2-220e-11e8-9280-aa6490cf7ffe.png)
![image](https://user-images.githubusercontent.com/18720307/37075943-29815a3a-220f-11e8-9703-954ad9409b52.png)
![image](https://user-images.githubusercontent.com/18720307/37075957-3bced294-220f-11e8-953d-36b4135106c2.png)
![image](https://user-images.githubusercontent.com/18720307/37075978-5360d10a-220f-11e8-8221-7442ea133cf6.png)
![image](https://user-images.githubusercontent.com/18720307/37075997-6977d560-220f-11e8-9e27-03e2ecac5eba.png)

Please do everything in Word file and submit everything to your folder in github..

**Comment by Nicole-Rutagengwa** [comment]
interesting task @kay@irufaan, and i guess the details of the products are helpful for the customers once they are making choice on what to buy.

**Comment by irufaan** [comment]
![image](https://user-images.githubusercontent.com/18720307/37081565-c5ad0426-2224-11e8-8c2b-86017d64f259.png)

**Comment by irufaan** [comment]
@KingKlaus ,, I checked your works,, Still not much details of products u added extra.. less image,, Do you wanna continue that work or thats it?

**Comment by KingKlaus** [comment]
Just this boss...most of the sites had no details...the pictures carry the details
