### ISSUE TITLE
Consumer Electronics

### ISSUE THREAD

**Issue by irufaan** [irufaan/team-kernel-competition#6]
We need find few products we can supply to customers about Consumer Electronics. At least We need 5 products in this category,, more is appreciable, 

1. All details of the product.
- Description of the product
- Few Images of the product
- Allow Customers to Customize the product ( custom needs such as process method, surface treatment, size, color, logo, etc.)
- Minimum orders that customers can order
- Payment method (L/C, T/T, Western Union etc)
- Delivery details
- Location of the factory, like from which City in China.

2. All Details of the Supplier
- Contact information (Phone Number, Email , factory name, Supplier Name , etc)
- For this category you can either have different factory or just from same factory,, its your choice
- Few Images of the factory and Supplier.
- What deal we have with the factory,, like how we are benefiting by selling products? like monthly salary or commission? or profit share. 

I can recommend some products you can look for,
1. Cellphone & Accessories : Original Unlocked Ios Phone 6 Plus 
2. Digital Devices : Sport Camera / 2.0 Inch Screen Action Camera / 1080P Full HD Sport DV
3. Audio & Video : Flat Screen 49 50 55 Inches Smart HD Color TFT LCD LED TV
4. Household Appliances : Best Quality Stainless Steel Shock Freezing Commercial Blast Freezer (AK11-D)
5. Cellphone & Accessories : Sport Stereo Wireless Bluetooth Private Label Headphone/Headset

Still you can choose whatever you want from this category.
Again if you still dont understand how you need present this details ,, I can show you sample of one product.. 

![image](https://user-images.githubusercontent.com/18720307/37078001-5b58f366-2218-11e8-8d29-d2901e9ca0c2.png)
![image](https://user-images.githubusercontent.com/18720307/37078108-de63e23e-2218-11e8-8a4b-892b63a65263.png)
![image](https://user-images.githubusercontent.com/18720307/37078019-77b385ee-2218-11e8-897e-f3bdad1f8c9f.png)
![image](https://user-images.githubusercontent.com/18720307/37078030-87e4aad8-2218-11e8-9ade-321733f0da89.png)
![image](https://user-images.githubusercontent.com/18720307/37078057-9e021bac-2218-11e8-82ef-65fa1bce0eeb.png)
![image](https://user-images.githubusercontent.com/18720307/37078084-bb86655c-2218-11e8-8f18-4d55183f3014.png)
![image](https://user-images.githubusercontent.com/18720307/37078095-cb520108-2218-11e8-93b0-816ffcb80f92.png)

Please give factory details and pictures too
Please do everything in Word file and submit everything to your folder in GitHub..

**Comment by Nicole-Rutagengwa** [comment]
okay got it !@irufaan..so let me work on it thanks if i need further explanations i willl let you know!

**Comment by Nicole-Rutagengwa** [comment]
by the way where i am supposed to upload this?under this is or in my folder?

**Comment by irufaan** [comment]
![image](https://user-images.githubusercontent.com/18720307/37078437-4c7fcae8-221a-11e8-9d3c-aa7b44d196ff.png)

**Comment by Nicole-Rutagengwa** [comment]
okay cool

**Comment by Nicole-Rutagengwa** [comment]
When you say they need to put logo ?what did you mean by this @irufaan

**Comment by Nicole-Rutagengwa** [comment]
Factory pictures🤔 we don’t have any factory so I can choose any by myself or?please make this point also clear @irufaan

**Comment by irufaan** [comment]
@lanicky yeah,, of cause, you can choose any factory pictures ,, get pictures and details from different source and combine and make into one..

**Comment by irufaan** [comment]
@lanicky about the logo is customization option,, for eg,, if someone from your country want buy a product from china to sell in your country,, they can even tell to the factory to put logo they want and color, quality, brand name etc,, because products are producing from factory, so they can change whatever they wish,,

**Comment by irufaan** [comment]
@lanicky Do you understand now? any question?

**Comment by Nicole-Rutagengwa** [comment]
Ohh okay I understand and I’m working on it will upload everything tomorrow!thanks n have a good night

**Comment by irufaan** [comment]
@lanicky ,, i checked your works, its ok,,

**Comment by Nicole-Rutagengwa** [comment]
Yayyyyyy 🧚🏾‍♀️🧚🏾‍♀️🧚🏾‍♀️Finally !thanks for your motivation I learned a lot throughout this reasearch☺️

**Comment by irufaan** [comment]
@lanicky ,, nice,, thats the main point,, learn something and understand what you need to improve ,, and you can use this project for even your resume, (CV) .. keep it up and work hard..
