### ISSUE TITLE
Furniture

### ISSUE THREAD

**Issue by irufaan** [irufaan/team-kernel-competition#7]
We need find few products we can supply to customers about Furniture. At least We need 5 products in this category,, more is appreciable, 

1. All details of the product.
- Description of the product
- Few Images of the product
- Allow Customers to Customize the product ( custom needs such as process method, surface treatment, size, color, logo, etc.)
- Minimum orders that customers can order
- Payment method (L/C, T/T, Western Union etc)
- Delivery details
- Location of the factory, like from which City in China.

2. All Details of the Supplier
- Contact information (Phone Number, Email , factory name, Supplier Name , etc)
- For this category you can either have different factory or just from same factory,, its your choice
- Few Images of the factory and Supplier.
- What deal we have with the factory,, like how we are benefiting by selling products? like monthly salary or commission? or profit share. 

I can recommend some products you can look for,
1. Furniture by Use : Customized Office Workstation with File Drawers Computer Cubicles
2. Furniture by Use : The Decent Luxury Cabinets for Kitchen with Particle Board
3. Chairs & Tables : Modern Dining Room Furniture Marble Top Stainless Steel Dining Table
4. Chairs & Tables : Modern Executive Wood Desk Manager Table Office Furniture
5. Cabinets & Beds : Antique Bedroom Furniture Set with Classic Bed (W808)

Still you can choose whatever you want from this category.
Again if you still dont understand how you need present this details ,, I can show you sample of one product.. 

![image](https://user-images.githubusercontent.com/18720307/37078824-9c432894-221b-11e8-9e27-90e901f3cec1.png)
![image](https://user-images.githubusercontent.com/18720307/37078854-adfc8d78-221b-11e8-9973-fc44d015808a.png)
![image](https://user-images.githubusercontent.com/18720307/37078882-bea1ab4a-221b-11e8-8fe8-e02629aa5b9b.png)
![image](https://user-images.githubusercontent.com/18720307/37078918-d2fcce26-221b-11e8-82f7-96fa3d98a80d.png)
![image](https://user-images.githubusercontent.com/18720307/37078949-e2b34e08-221b-11e8-889e-abaa3c50a424.png)
![image](https://user-images.githubusercontent.com/18720307/37079078-474cc092-221c-11e8-8af6-52673ac453e3.png)
![image](https://user-images.githubusercontent.com/18720307/37079099-5cee56f4-221c-11e8-9e9d-9c5401fe0325.png)
![image](https://user-images.githubusercontent.com/18720307/37079163-9ae711b2-221c-11e8-99bb-186fa085ce0b.png)
![image](https://user-images.githubusercontent.com/18720307/37079187-ae389312-221c-11e8-8adc-765fa9fb2b12.png)
![image](https://user-images.githubusercontent.com/18720307/37079202-bceaa04e-221c-11e8-834a-6aa89d3e5176.png)
![image](https://user-images.githubusercontent.com/18720307/37079220-cd671628-221c-11e8-9bc1-186a3cb0c223.png)
![image](https://user-images.githubusercontent.com/18720307/37079247-eb1ec0ee-221c-11e8-8bdf-3665405c3fd3.png)

Please use your laptop to do the task, so that most of the issues that you face from phone will go.. 
Please give factory details and pictures too
Please do everything in Word file and submit everything to your folder in GitHub..

**Comment by irufaan** [comment]
@Ricil ,, have you done correcting your works?

**Comment by Ricil** [comment]
YEs will send when I get home

**Comment by Ricil** [comment]
Was it ok
