### ISSUE TITLE
Summary- The Background of Self-Selection

### ISSUE THREAD

**Issue by irufaan** [irufaan/team-kernel-competition#8]
@Hasanzjnu is the one who will lead this task.  

The background of the self-selection proposition of no more than 2000 words.

- How we did this project (you can explain that GitHub is the working platform we used to complete this project.) Please include some screenshots from Github,

- How everyone in the team assigned tasks. screenshots as a evidence. 

- Role of everyone in the team. Introduction of team members.

##  **`Please be serious about this Task, because from this document we all get scores.`**

**Comment by Ricil** [comment]
Hassan I ll do 3 and 4

**Comment by irufaan** [comment]
Nice work
