### ISSUE TITLE
Summary- A brief introduction

### ISSUE THREAD

**Issue by irufaan** [irufaan/team-kernel-competition#9]
@lanicky is the one who will lead this task.

A brief introduction of no more than 800 words;

- explaining the goal of this project.

- Ideas

- practices, please include screenshots from GitHub.

- highlights

# **`## Please be serious about this Task, because from this document we all get scores.`**

**Comment by Nicole-Rutagengwa** [comment]
okay!no problem @irufaan

**Comment by Nicole-Rutagengwa** [comment]
let's do this!@klaus

**Comment by KingKlaus** [comment]
Just do the work iwe

**Comment by KingKlaus** [comment]
File uploaded for brief intro please have a look at it

**Comment by irufaan** [comment]
Nice work ,,,
